[project]
name = "parser-mouser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.26.0",
    "beautifulsoup4>=4.14.3",
    "deep-translator>=1.11.4",
    "lxml>=6.1.0",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "tqdm>=4.67.3",
    "typing-extensions>=4.15.0",
    "urllib3>=2.6.3",
]
